name: restkuy
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    user: root
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
    environment:
      - PORT=${PORT}
    ports:
      - "1323:1323"
    depends_on:
      - postgres
    user: root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
